Q02. Refer to salaries.xlsx file and solve following questions.

a. Check head of the dataframe.

b. Find out details about no. of entries & no. of columns in the data frame.

c. What is the average base pay?

d. What is the highest amount of overtime pay in the dataset?

e. What is the job title of JOSEPH DRISCOLL?

f. How much does JOSEPH DRISCOLL make (including benefits)?

g. How many unique job titles are there?

h. What are the top 5 common jobs?

In [2]:
import pandas as pd

In [3]:
df = pd.read_excel(r"C:/Users/ASUS/Downloads/Salaries.xlsx")
df

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,ANTIONETTE GRIFFIN,CLINICAL NURSE SPECIALIST,169572.08,0.00,250.00,NaN,169822.08,169822.08,2011,NaN,San Francisco,NaN
996,997,KATHERINE MAH,CLINICAL NURSE SPECIALIST,169572.06,0.00,250.00,NaN,169822.06,169822.06,2011,NaN,San Francisco,NaN
997,998,CHRISTINE DAVENPORT,CLINICAL NURSE SPECIALIST,169572.05,0.00,250.00,NaN,169822.05,169822.05,2011,NaN,San Francisco,NaN
998,999,ANNE HUGHES,CLINICAL NURSE SPECIALIST,169572.01,0.00,250.00,NaN,169822.01,169822.01,2011,NaN,San Francisco,NaN
999,1000,JOHN FAZIO,CLINICAL NURSE SPECIALIST,169572.00,0.00,250.00,NaN,169822.00,169822.00,2011,NaN,San Francisco,NaN

a. Check head of the dataframe

In [4]:
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

b. Find out details about no. of entries & no. of columns in the data frame

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Id                1000 non-null   int64
 1   EmployeeName      1000 non-null   str
 2   JobTitle          1000 non-null   str
 3   BasePay           1000 non-null   float64
 4   OvertimePay       1000 non-null   float64
 5   OtherPay          1000 non-null   float64
 6   Benefits          0 non-null      float64
 7   TotalPay          1000 non-null   float64
 8   TotalPayBenefits  1000 non-null   float64
 9   Year              1000 non-null   int64
 10  Notes             0 non-null      float64
 11  Agency            1000 non-null   str
 12  Status            0 non-null      float64
dtypes: float64(8), int64(2), str(3)
memory usage: 101.7 KB

c. What is the average base pay?

In [6]:
df["BasePay"].mean()

np.float64(145663.9982)

d. What is the highest amount of overtime pay in the dataset?

In [7]:
df["OvertimePay"].max()

np.float64(245131.88)

e. What is the job title of JOSEPH DRISCOLL?

In [8]:
df[df["EmployeeName"]=="JOSEPH DRISCOLL"]["JobTitle"]

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: str

f. How much does JOSEPH DRISCOLL make (including benefits)?

In [9]:
df[df["EmployeeName"]=="JOSEPH DRISCOLL"]["TotalPayBenefits"]

24    270324.91
Name: TotalPayBenefits, dtype: float64

g. How many unique job titles are there?

In [10]:
df["JobTitle"].unique()

<StringArray>
[    'GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
                    'CAPTAIN III (POLICE DEPARTMENT)',
               'WIRE ROPE CABLE MAINTENANCE MECHANIC',
       'DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)',
                          'ASSISTANT DEPUTY CHIEF II',
                 'BATTALION CHIEF, (FIRE DEPARTMENT)',
                     'DEPUTY DIRECTOR OF INVESTMENTS',
             'CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)',
   'ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)',
                        'EXECUTIVE CONTRACT EMPLOYEE',
 ...
 'ELECTRONIC MAINTENANCE TECHNICIAN ASSISTANT SUPERV',
                                'CLINICAL PHARMACIST',
                                 'DEPARTMENT HEAD II',
                          'CLINICAL NURSE SPECIALIST',
                                      'NURSE MIDWIFE',
           'ELECTRICAL TRANSIT MECHANIC SUPERVISOR I',
                                          'MANAGER V',
              'ATTORNEY FOR THE PUBLIC ADMINISTRATOR',
                               'CHIEF DEPUTY SHERIFF',
                              'SENIOR DEPUTY SHERIFF']
Length: 113, dtype: str

h. What are the top 5 common jobs?

In [11]:

df["JobTitle"].value_counts().head()

JobTitle
FIREFIGHTER                           133
LIEUTENANT, FIRE DEPARTMENT            62
FIRE FIGHTER PARAMEDIC                 43
CAPTAIN, FIRE SUPPRESSION              42
BATTALION CHIEF, (FIRE DEPARTMENT)     41
Name: count, dtype: int64